### PR TITLE
Un-Hardcode file locations

### PR DESCRIPTION
**Pull request by CrezyDud**
I've un-hardcoded the file locations so you can place this where ever you want
please add dependencies to the readme <-( added them ) you have to test more, building and .dev_mode have worked ( I couldn't test everything please you do that )

I'll do it for V2.0 too soon

### CODE REVIEW

**Comment by CrezyDud** [comment]
I finished it for your v2.0 but i cant merge,
maybe you haven't set it public but i was able to see it anyway?
anyway set it to public or add me to it

**Comment by CrezyDud** [comment]
bash shortcut still doesn't work, even though I followed the wiki..

**Comment by Nonethousand** [comment]
> I've un-hardcoded the file locations so you can place this where ever you want
> please add dependencies to the readme <-( added them ) you have to test more, building and .dev_mode have worked ( I couldn't test everything please you do that )
> 
> I'll do it for V2.0 too soon

ok i will
i will copy it from your fork because i have no idea what dependencies sm64lbuilder requires

**Comment by Nonethousand** [comment]
> I finished it for your v2.0 but i cant merge,
> maybe you haven't set it public but i was able to see it anyway?
> anyway set it to public or add me to it

ok

**Comment by Nonethousand** [comment]
> bash shortcut still doesn't work, even though I followed the wiki..

what bash shortcut

**Comment by CrezyDud** [comment]
the one where you just type SM64LBuilder in the command line and it opens
it was in your original readme:

> If you have ran main.sh at least once all you have to do to run it again is to run
> 
> SM64LBuilder
> 
> in the terminal.

**Comment by CrezyDud** [comment]
if you like all the changes you can merge, tell me about anything i should change

**Comment by Nonethousand** [comment]
> the one where you just type SM64LBuilder in the command line and it opens
> it was in your original readme:
> 
> > If you have ran main.sh at least once all you have to do to run it again is to run
> > SM64LBuilder
> > in the terminal.

It should work since the script puts an alias command in a .bash_alias file

**Comment by CrezyDud** [comment]
thanks

**Pull request merged**
